apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: object-param-result-
spec:
  params:
    - name: gitrepo
      value:
        commit: "sha123"
  taskSpec:
    params:
      - name: gitrepo
        type: object
        properties:
          url: {type: string}
          commit: {type: string}
        default:
          url: "github.example.com"
    results:
      - name: object-results
        type: object
        properties:
          IMAGE_URL: {type: string}
          IMAGE_DIGEST: {type: string}
    steps:
      - name: echo-object-params
        image: bash
        args: [
          "echo",
          "--url=$(params.gitrepo.url)",
          "--commit=$(params.gitrepo.commit)"
        ]
      - name: write-object-result
        image: bash:latest
        script: |
          #!/usr/bin/env bash
          echo -n "{\"IMAGE_URL\":\"ar.com\", \"IMAGE_DIGEST\":\"sha234\"}" > $(results.object-results.path)
