name: 'woke'

permissions:
  contents: read

on:
  - pull_request
jobs:
  woke:
    name: 'woke'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
      - name: 'Checkout'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@d6babd6899969df1a11d14c368283ea4436bca78 # v44.5.2
        with:
          write_output_files: true
          files: |
            **

      - name: 'woke'
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
        with:
          # Cause the check to fail on any broke rules
          fail-on-error: true
          woke-args: ${{ steps.changed_files.outputs.all_changed_files }}
